apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:gfvsIUNdnV+oJbm3IRUb6zZeu/0H7rb/+euESE7XHJc65FFG5BRpoXHQdQ/f1/bsdfP/JN0=,iv:mq419cECSDJwOqvKxEDpMce0ucQ7v9BcrGyY7uVNRpE=,tag:bD20dhUnC1NcMwbS8KCk3w==,type:str]
sops:
  age:
    - recipient: age1hu97g9evhacj90y52hl3y3zrjst47s90cq94fp6d4p3exlzfv5hsxfl78r
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNi9WTmJzVnM5N1dtUmQ3
        SDQ0d2NKS25UbHo3V0NqQWxwK3EvaVE3N2xrCkYzenlJVTVXUDQ0MTR1YzFJbGwy
        TDQrZmpxMlVQR0ZSZE9GczdQQVlaT3MKLS0tIHUvb1AwTk1TTm9sT3lrOUROSUFn
        akhNY2FsMGI4VW1ocjdJZVl5M0dKaDAKgpz6547Sg+IYtxlMnhGYqMlEWYob7qgn
        Xf+2FgEKYbKoiXAtubzP4R9dPGa4rkyaa/xJ0KK6d2IbaQM5Y/LYyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-05T12:23:18Z"
  mac: ENC[AES256_GCM,data:c/cdNL+fSjZ+kxECPdv8FRpzdrOb425vJOGNio1ogVYUFjaT4y4z5mV6Z4EQFk7EdkylbAYK6MiCxxMg3tPoV6gNLJtMDA49WkxjjEi9QwcZTVfHqogOtOeH+sm3czjFxJRDU7ihfQvK6Olaf0U8AikDv5Jiu5xegJoaFtF/X4w=,iv:QQu1SY4wrAq4jmH62IyQi0hvXIjVQruGabzbbKhNC7U=,tag:kJNI4omZis5wu5gqJokm7w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
