apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:L+ExhNsf+vcYoaQ=,iv:Sowcrw1iWZyWESQvoRzH85EqS+Jt9LC/IaMIMbEZrQo=,tag:3qKDIH2uXZ34yeQVV8g4OA==,type:str]
sops:
  age:
    - recipient: age1hu97g9evhacj90y52hl3y3zrjst47s90cq94fp6d4p3exlzfv5hsxfl78r
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0YXRreXlrNFlXQnNjTC90
        N1N3OWdFOGYwL25HMkh5UUhjMmRUVU96amk0CjBrUkNEVmNwa25TT0lCVTB0YnA5
        YlNaTjFmdUFwN3BPOVpKd01WZnJoWmMKLS0tIHRQaWNBS1FZaWh3YUtBalQ0VFNI
        TmtRVVVCb2xwang4Um1jRWY1ei9wd1UKRpN5ARk3s5WJlQwzbvjtMeI/gv/I2KKZ
        dAzBVPKWt5PwI9FbQ8n7fQw1lWnmRKLFqpeW6QF8h6ZoA6YWPrV0Fw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-05T12:23:18Z"
  mac: ENC[AES256_GCM,data:9vHxgXQdU2TDll0Ru6KoVNj/KX0535AANEiJ1xLKECRSkP1T+3SdG1v/efJofDoIIGQGRjPrtpjDfucr7k8uv6pi5dBg5uCOsIlxAD5PSsebd46Cy+7Vd/DuwyBt/yLhvPk3osqS2l76BkUElLiE5KhzStJJ4jtFbDETtFdmCF4=,iv:uHqyKIia9xm6/EMHhea1FCYPyPUDiLqHfOLx45rMI0c=,tag:NigQmteAwSdos3/jKyBNAg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
