apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:5PttAcbloixCbRjdLnSf8r0m1U62U6Ljqz4Gyka5iXA=,iv:+Jfr5/xO5MlJE13lxrW2wRHXNX5ejGtf/2l8GpPqw1E=,tag:l2OoF9J1TzvR3QmoIyGRmg==,type:str]
sops:
  age:
    - recipient: age1hu97g9evhacj90y52hl3y3zrjst47s90cq94fp6d4p3exlzfv5hsxfl78r
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1QitUdVZrV0o2VktnRmxM
        K1RjQ3B0QUtSaDZsOEFlakJGb05paGptL2lJCmlWODhCalYvdjh6a1B2TENIT2Zw
        THFicGNadDF3SDhRdHlMdHozMFRRK1EKLS0tIFJaWG03YW1ObDlJUFdWK3paVkxP
        SDdic1RKQkk1YlRHVEh5bVFtRTJBaVEKLsGgs1PPVR6pAiWk3G2N6DGL77RypQ9H
        7dtnTN01+OEUsJXJH0fTU6px7zP5IQGD9sFN6KBCvKBacWpWelcNKA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-05T12:23:18Z"
  mac: ENC[AES256_GCM,data:gtFWv3w8N71zq7NNdatfeV9b6lf25uNusQQT5cRNSHK7rMvYgGt67MLSbZaxMYBhS8tDb4MnTjjN7fH141aSp1BJVao9Ptu+aE5EHJbZFaJd7sBWYZ3481UiQiwFzampfzokawl4bmmS2x64yCLM0Qi4g2YSTLRjXfo17rh+0gc=,iv:v67V1je5c3rqgj0S34F6MxoJpaX3XL41nIe3t0p+LBM=,tag:j1brOAb2v0XfKVWdxMEN9g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
