apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:YmLPjN8D0G62gTzSQ6JWnllnaxekWlFl2HdjD7IgexWtAtQkjHggeqke+z+J/pxGF5cvIxKPAfx3LH9A7tcdJbpUtT88Wsx6ilWWuKQZoID3pY8Iq9Dtm1Wi+In8MNeXi9KLtkB7EMn9NEU8YFFaSz8v1dFeEK0ZDAh9UpjOwPWPmOZnrBtREzefDjVRjcqF7Az+qb9+soVSZBb5tF0nRHBZUfJh/F07ZqGb5Yhj/6J5a2hn,iv:cnQiPLWS2DJFPmOEdbp1ACDsPiFRcO0mNT2imFBvH6Y=,tag:fNyxq8Fwk/2YHpENNnml0A==,type:str]
sops:
  age:
    - recipient: age1hu97g9evhacj90y52hl3y3zrjst47s90cq94fp6d4p3exlzfv5hsxfl78r
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwb2JwRTh2YmkrOUpaeUgx
        NWp2dE8yMlhVMGxoTWE1VkNEdU5ramtHU1NzCkZTalJkUmNVNEhzdFQrT0dGWFJ1
        V3hLbm1TMEduNTlGdmpJb2NrVUlnWVUKLS0tIDdxMk1tTmFnTjZCUG0vSVluUU5D
        UGFKL1NPRElEcTRPeGY1Z1B0MWJOTkkKRMExSxFC5pmJOqzHbA8hhiKXRMqsmvSm
        Um9dq04KJ0Y7JKlZs54qO2kM0lGHKuaLvq/dAenoE6lxesDjGb851Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-05T12:23:18Z"
  mac: ENC[AES256_GCM,data:SWpwtLfiOEDMq3gBuuZ6fP6xmkZNr504ik2Wg1eUBUebA36N8GDPTFyOpLNIBvkx7jnUAo7W6jHBT1dRpRThwRDeP/AU0mvRKUtgSk5ug8SFYW0Na34cgaWMDC3PyAwTWoKr67ZS40xt0V8Hd+GeNJtu2B+Q+OLI5CM+VgROA4Y=,iv:VrVntImrSQVRq75zRtZ2Is8IT4RH0ah55Z76mDVKGPQ=,tag:kl/kA0XTHhXwODbZVH6VKg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
