apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:L9X3Jb2BT4UFYbWVg4pk5YEmuvVcwCwaZp3HPAO0Gl7KIsSHaHNoTy2GQEyMYRdcSqxOy9I=,iv:7U8G00lrWOT5n4/OaWy329sx7OA/3fJZG7RqKOcYn2A=,tag:TTLNhN5NhGjYeEK98E2C4g==,type:str]
sops:
  age:
    - recipient: age1hu97g9evhacj90y52hl3y3zrjst47s90cq94fp6d4p3exlzfv5hsxfl78r
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGci9OWXpsQmtnUTZOV2lJ
        UzNibStmazBQblJlRm0zcE1ORFZrdFV6ekdvCmUvL3oyTXJhZmxUTElxSFlidnZR
        T2Q4TE5zNCtpYStNOGVIWEs1RTM5L1EKLS0tIFhlQ3BPZUJ4SnBISWR2RXlDZG1O
        d21LbnJKMGFiNDRaaDVOUzJKRzZ1Y2sKq3P5TYyeDeXl8DXsNf5cT9QnqOTUe7cV
        ZCXrDm5nHf6n7Ma2p+BuEOG9EHMeHNYGTnIE/rJzgnQMLOZytyqZuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-05T12:23:17Z"
  mac: ENC[AES256_GCM,data:Lw4BgjXdgUcUnXeSp61xBPuaQDjvKT+7Pxur7Jv8dJF8Z5mbTjl4p2R4RkTuhc6YTCWFLLvgg59cKFXiIbcN7aJUUd3XvnDDlhG/KfgSCy41y4awPHd+uZSQlQE0R5cLSfhQT2RfAeN1VXscOXBDiUcR3QGcK+5c/SwJf8WeJos=,iv:0XBBtmJwjKIJbY7BZAsLM45g4F3YGrJbhL3aRemYBdA=,tag:IE34zPmjGXVER2xycyon1Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
